[PR/#11] 홈 뷰 UI 구현, 로직 기능 구현
Movielity/Movielity_iOS pull request #16
Opened 2024-10-12 11:34 UTC by MileyJump

## 📝작업 내용

> 홈 뷰(Trending View)의 전체 스크롤을 테이블뷰에서 스크롤뷰로 변경해서 구현했습니다.
> 테이블뷰셀 안에 컬렉션뷰로 구현했던 부분을 테이블뷰를 제거 후 컬렉션뷰로만 수정해서 구현했습니다.
> 네트워크 API Movie, Series 응답값으로 NowHotMovie, NowHotSeries 컬렉션뷰 셀 포스터 이미지를 설정했습니다!
> Main 포스터(HomeView의 PosterImageView)는 Movie 와 TVSeries 섹션에 보여질 미디어 중 랜덤으로 하나를 가져와 이미지 설정을 했습니다!

## 💬리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요 :)

2024-10-12 13:55 UTC, rkdtnlzl requested changes
key값 다시 기본값으로 바꾸셔야할거같습니다!

2024-10-12 13:55 UTC, rkdtnlzl commented on Movielity/Global/Resources/APIKey.swift
> +    static let tmdbKey = "af72282e0011f60e2f29df4c833ecfe7"
다시 기본값으로 돌려주세요~

2024-10-12 13:55 UTC, rkdtnlzl commented on Movielity/Presentation/Home/HomeViewController.swift
> +            }
이미 bind를 사용하면 메인스레드 실행을 보장하기 때문에  
`.observe(on: MainScheduler.instance)`  를 생략해도 좋을거같습니다~

2024-10-12 13:55 UTC, rkdtnlzl commented on Movielity/Presentation/Home/HomeViewModel.swift
> +            .subscribe(with: self, onNext: { owner, movies in
영화&시리즈 결합하는 부분을 bind로 하셨는데 이 부분은 왜 subscribe로 하셨나요??

2024-10-12 19:41 UTC, Acasiax requested changes
API 부분만 수정 부탁드립니다. 수고 하셨습니다~!

2024-10-13 06:15 UTC, Acasiax approved these changes
수고하셨습니다~!

2024-10-13 06:22 UTC, MileyJump commented on Movielity/Global/Resources/APIKey.swift
> +    static let tmdbKey = "af72282e0011f60e2f29df4c833ecfe7"
넵 알겠습니다!

2024-10-13 06:23 UTC, MileyJump commented on Movielity/Presentation/Home/HomeViewController.swift
> +            }
넵! 좋은 의견 감사합니다~ 반영하겠습니다!

2024-10-13 06:26 UTC, rkdtnlzl approved these changes
고생하셨습니다~ 커밋 컨벤션 다음부터는 지켜주셔야할거같습니다 :) 

저도 컨벤션 지키기 어렵네요,,ㅎ

2024-10-13 06:33 UTC, merged